blank_issues_enabled: true
contact_links:
  - name: Frequently Asked Questions
    url: https://gcn.nasa.gov/docs/faq
    about: Check here for answers to common questions.
  - name: User Support
    url: https://gcn.nasa.gov/docs/faq
    about: Submit user support questions (such as questions about your account) here.
